# Python Fundamentals 

##  _Functions_ 

In [1]:
def say_hello(name): 
    print ("Hello " + name + "!")

In [2]:
say_hello('Aiym')

Hello Aiym!


In [3]:
def welcome(name = 'student', location = 'the course "Introduction to Data Science"'): 
    print("Hello, "+name + "! Welcome to "+ location)

In [4]:
welcome()

Hello, student! Welcome to the course "Introduction to Data Science"


In [5]:
welcome('Aisha', 'home')

Hello, Aisha! Welcome to home


## Booleans


In [6]:
bird_fly = True 
if bird_fly: 
    print ('It is a swan')
else: 
    print('It is a penguin')

It is a swan


*Comparison Operators*

In [7]:
2>1

True

In [8]:
2<3<4<5<6

True

In [9]:
2<3<1

False

In [10]:
4!=5

True

In [11]:
3>=1

True

In [12]:
'M'<'m'

True

In [13]:
1<'a'

TypeError: '<' not supported between instances of 'int' and 'str'

## _While - Loop_ 

In [14]:
i = 1
while i<=4: 
    print(i) 
    i = i + 1

1
2
3
4


In [15]:
mylist  = [1,2,'a','cat',3.3]
for i in mylist: 
    print(i)

1
2
a
cat
3.3


In [16]:
mylist[3]

'cat'

In [17]:
mylist[0]+mylist[4]

4.3

# Advanced Data Structures

* Tuples 
* Lists  
* Dictionaries 
* Sets

## _Tuples_

In [18]:
tuple_nums = (1,2,3,4)
tuple_str = ('A','B','C')
tuple_mixed = ('Hi',123,False)

In [19]:
tuple_nums

(1, 2, 3, 4)

In [20]:
tuple([0,1,2])

(0, 1, 2)

In [21]:
tuple([1])

(1,)

In [22]:
l1= [1,2,3,4]
l2 = ['A','B']
t = (*l1,*l2)
t

(1, 2, 3, 4, 'A', 'B')

In [23]:
person = ('Kate', 20,False)
name,age,registred = person
name

'Kate'

In [24]:
# Get tuple length
len(person)

3

_Convert tuple to LIST_

In [25]:
#Convert tuple to List 
tup = (1,2,3)
list(tup)

[1, 2, 3]

In [26]:
l = [*tup, 4,5,6,7,8]
l

[1, 2, 3, 4, 5, 6, 7, 8]

_Convert tuple to SET_

In [27]:
s = set(tup)
s

{1, 2, 3}

In [28]:
s ={*tup}
s

{1, 2, 3}

_Convert tuple to STRING_

In [29]:
str(tup)

'(1, 2, 3)'

### Exercises
1. Write a program to hold a small database of food items and their costs using two lists. 
2. Create a 2D array of zero integers, fill with some numbers and print out the full array then print out some slices from the array. 
3. Create a list with the names of 10 'friends'. Create a second matching list with their years of birth. 

## _Dictionary_ 

In [30]:
user_id = {'Ali':'123','Nick':'124'}
emp_dict = {}
user_id['Ali']

'123'

In [31]:
user_id['Eric'] = '135'
del(user_id['Ali'])
user_id

{'Nick': '124', 'Eric': '135'}

In [32]:
a = {'sub_dict':{'b':True},'list':[1,2,3]}
a['sub_dict']['b']

True

In [33]:
a['list'][1]

2

In [34]:
dict1 = {int:1, float:2}
dict1[int]

1

In [35]:
dict2={1:'Gold',2:'Silver',3:'Bronze'}
dict2[2]

'Silver'

_More ways to create a Python dictionary_

In [36]:
# Using the dict() constructor 
dict([('A','1'),('B','2'),('C','3')])

{'A': '1', 'B': '2', 'C': '3'}

In [37]:
#Using comprehensions 
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [38]:
#Using dict.fromkeys
letters = ('A','B','C')
letter_order = dict.fromkeys(letters, None)
letter_order

{'A': None, 'B': None, 'C': None}

In [39]:
# Parse JSON dictionary 
import json 
jsonstring  = '{"name":"Ben", "age": "20", "student":true}'
json.loads(jsonstring)

{'name': 'Ben', 'age': '20', 'student': True}

_Using Python dictionaries_

In [40]:
#Dictionary view objects 
user_ids = {'Ali':'123','Nick':'124', 'Ben':'101'}
user = user_ids.keys()
user_ids['Kate'] = '222'
print(user)

dict_keys(['Ali', 'Nick', 'Ben', 'Kate'])


In [41]:
del(user_ids['Kate'])

In [42]:
user_ids['Kate']

KeyError: 'Kate'

In [43]:
#Get the keys from dictionary 
list(user_ids)

['Ali', 'Nick', 'Ben']

In [44]:
sorted(user_ids)

['Ali', 'Ben', 'Nick']

In [45]:
# Check if a key exists in  a Python dictionary 
'Ali' in user_ids

True

In [46]:
'Kate' not in user_ids #not in 

True

In [47]:
# Getting the length 
len(user_ids)

3

In [48]:
for username, userid in user_ids.items(): 
    print(username,' : ', userid)

Ali  :  123
Nick  :  124
Ben  :  101


In [49]:
#Merging dictionaries 
dict1 = { 'a': 1, 'b': 2 }
dict2 = { 'b': 3, 'c': 4 }
merged = { **dict1, **dict2 }
print (merged)

{'a': 1, 'b': 3, 'c': 4}


In [50]:
# Comparing Python dictionries 
first_dict  = { 'a': 1, 'b': 2, 'c': 'a string' }
second_dict = { 'a': 1, 'b': 2, 'c': 'a string' }
first_dict == second_dict

True

In [51]:
first_dict  = { 'a': 1, 'b': 2, 'c': 'a string' }
second_dict  = { 'b': 2, 'a': 1, 'c': 'a string' }
first_dict == second_dict

True

### Exercises
1. You have to read a statement of the 1st exercise(Lists) and write a program with a dictionary. 
2. Try to execute problem of 10 'friends'

## Numpy arrays - An Introduction 

_Using NumPy_

In [52]:
import numpy as np 
a = np.arange(9,dtype = 'float')
print(a) 

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [53]:
a.shape = (3,3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [54]:
b = a**2+1+3
print(b)

[[ 4.  5.  8.]
 [13. 20. 29.]
 [40. 53. 68.]]


In [55]:
a= np.ones((3,3), dtype = float)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
# Slicing and Addresing Arrays
a = np.arange(9,dtype = 'float')
print(a[1:5]) # A slice from element 1 to element 4 

[1. 2. 3. 4.]


In [57]:
a.shape = (3,3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [58]:
print(a[1,1])

4.0


### Exercises
1. Formulate and output an array with the size N (you choose), that consists of N odd numbers
2. Let be given N(you choose), and the first member A and difference D of arithmetic progression/sequence. Output the first N numbers 
of that sequence
3. Let be given N(you choose), and the first member A and difference D of geometric progression/sequence. Output the first N numbers of that sequence
4.  Let be given N(you choose). Output an array of the size N that contains first N elements of Fibonnacci numbers
5. Let be given N(you choose but greater than 2), A and B. Write a program to output an array of the size N, first element of which is equal to A,the second - to B, and each subsequent element is equal to the sum of all the previous ones. 